#!/usr/bin/env tsx
import {extendedTypes as expected} from './spec/expected.js'
import {presentationFormat} from "./src/rfc1035.js";
import {CLASS, RecordType} from "./src/constants.js";

process.stdout.write(`; This file was generated by generate_expected.ts. Any modifications will be lost.
example.xa.     IN  3600    NS    ns1.example.xa.
ns1.example.xa. IN  3600    A     127.4.1.1
ns1.example.xa. IN  3600    AAAA  fda1:b2:c3::127:4:1:1
`);
for (const [type, config] of Object.entries(expected)) {
    const name = config.host.split('.');
    for (const rdata of config.records) {
        process.stdout.write(presentationFormat({
            NAME: name,
            TYPE: RecordType[type as keyof typeof RecordType],
            CLASS: CLASS.IN,
            TTL: 3600,
            RDATA: rdata,
            RDLENGTH: 0,
        }) + '\n');
    }
}