options {
    listen-on { 127.0.0.0/8; ::1/128 }
}

view "ns1." {
    match-destinations { 127.1.0.1; fda1:b2:c3::127:1:0:1; };
    file "COMMON/root-zone"
    file "COMMON/arpa"
}

view "ns2." {
    match-destinations { 127.1.0.2; fda1:b2:c3::127:1:0:2; };
    file "COMMON/root-zone"
    file "COMMON/arpa"
}

view "dnssec-root" {
    match-destinations { 127.1.0.3; fda1:b2:c3::127:1:0:3; };
    zone "." {
        file "../../.zone.signed"
        file "COMMON/arpa"
    }
}

# internal resolver on one server
view "recursive" {
    match-destinations { 127.3.0.53 }
    recursion yes;
}

view "ns1.xa." {
    match-destinations { 127.2.0.11; fda1:b2:c3::127:2:0:11; };
    zone "xa" {
        type primary;
        file "COMMON/xa";
    }
}

view "ns2.xa." {
    match-destinations { 127.2.0.12; fda1:b2:c3::127:2:0:12; };
    zone "xa" {
        type primary;
        file "COMMON/xa";
    }
}

view "ns1.xb." {
    match-destinations { 127.2.0.13; fda1:b2:c3::127:2:0:13; };
    zone "xb" {
        type primary;
        file "COMMON/xb"
    }
}

view "ns2.xb." {
    match-destinations { 127.2.0.14; fda1:b2:c3::127:2:0:14; };
    zone "xb" {
        type primary;
        file "COMMON/xb";
    }
}

# Include test case specific configuration
#
# Basic-TP
import Basic-TP/basic01/basic01.cfg
# Connectivity-TP
import Connectivity-TP/connectivity04/connectivity04.cfg
# Consistency-TP
import Consistency-TP/consistency05/consistency05.cfg
import Consistency-TP/consistency06/consistency06.cfg
# Delegation-TP
import Delegation-TP/delegation01/delegation01.cfg
import Delegation-TP/delegation02/delegation02.cfg
import Delegation-TP/delegation03/delegation03.cfg
# DNSSEC-TP
import DNSSEC-TP/dnssec03/dnssec03.cfg
import DNSSEC-TP/dnssec10/dnssec10.cfg
import DNSSEC-TP/dnssec16/dnssec16.cfg
# Nameserver-TP
import Nameserver-TP/nameserver15/nameserver15.cfg
# Zone-TP
import Zone-TP/zone09/zone09.cfg

# Other
#
# Methods
import MethodsV2/methodsv2.cfg
# Engine
import Engine/Recursor-PM/recursor.cfg